### ISSUE TITLE
MQTT Client not working

### ISSUE THREAD

**Issue by boerjb** [markussiebert/homeassistant-addon-vzlogger#2]
Hi Markus,

first of all thanks for the Addon. I was able to get readings from my power meter. But I'm not able to get the data into HA. I did enable the MQTT client in the config like this:

"mqtt": {
    "enabled":  true,
    "host": "192.168.x.xxx",
    "port": 1883,
    "topic": "vzlogger/data"
    "retain": false
 }

In the log the following error appears:

[Nov 02 18:50:13][mqtt] mosquitto_connect failed. res=3! Stopped!

**Comment by markussiebert** [comment]
This is my mqtt config block, that is working:

```
"mqtt": {
        "enabled": true,
        "host": "192.168.1.11",
        "port": 1883,
        "id": "vzlogger",
        "cafile": "",
        "capath": "",
        "certfile": "",
        "keyfile": "",
        "keypass": "",
        "keepalive": 30,
        "topic": "vzlogger/data",
        "user": "vz",
        "pass": "somepass",
        "retain": false,
        "rawAndAgg": false,
        "qos": 0,
        "timestamp": false
    },

**Comment by ToPitz** [comment]
@boerjb Most properly you will need to specify username and password for the mqtt broker.
If using the mosquitto plugin: Since version 6 anonymous login isn't allowed anymore. I ran into similar issues. When specifying a user and password for the broker vzlogger doesn't complain anymore about disconnecting.
